# backend/utils/pdf_generator.py
import markdown
from weasyprint import HTML
import tempfile
import os

def convert_markdown_to_pdf(markdown_path, pdf_output_path):
    """
    Convert a markdown file to PDF
    
    Args:
        markdown_path: Path to the markdown file
        pdf_output_path: Path where to save the PDF
    
    Returns:
        Path to the generated PDF file
    """
    # Read markdown content
    with open(markdown_path, 'r', encoding='utf-8') as f:
        markdown_content = f.read()
    
    # Convert markdown to HTML
    html_content = markdown.markdown(
        markdown_content,
        extensions=[
            'markdown.extensions.tables',
            'markdown.extensions.fenced_code',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc'
        ]
    )
    
    # Add styling
    styled_html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <title>FinForensic Report</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                line-height: 1.6;
                margin: 2cm;
            }}
            h1, h2, h3, h4 {{
                color: #2c3e50;
            }}
            h1 {{
                border-bottom: 1px solid #eee;
                padding-bottom: 10px;
            }}
            table {{
                border-collapse: collapse;
                width: 100%;
                margin: 20px 0;
            }}
            th, td {{
                border: 1px solid #ddd;
                padding: 8px;
            }}
            th {{
                background-color: #f2f2f2;
            }}
            code {{
                background-color: #f7f7f7;
                padding: 2px 4px;
                border-radius: 3px;
                font-family: monospace;
            }}
            pre {{
                background-color: #f7f7f7;
                padding: 10px;
                border-radius: 5px;
                overflow-x: auto;
            }}
            blockquote {{
                margin: 0;
                padding-left: 15px;
                border-left: 4px solid #ddd;
            }}
            img {{
                max-width: 100%;
            }}
            a {{
                color: #3498db;
                text-decoration: none;
            }}
            a:hover {{
                text-decoration: underline;
            }}
            .footer {{
                margin-top: 50px;
                text-align: center;
                font-size: 0.8em;
                color: #7f8c8d;
            }}
            .page-break {{
                page-break-after: always;
            }}
        </style>
    </head>
    <body>
        {html_content}
        <div class="footer">
            Generated by FinForensic System
        </div>
    </body>
    </html>
    """
    
    # Create a temporary HTML file
    with tempfile.NamedTemporaryFile(suffix='.html', delete=False) as temp_html:
        temp_html_path = temp_html.name
        temp_html.write(styled_html.encode('utf-8'))
    
    try:
        # Convert HTML to PDF
        HTML(filename=temp_html_path).write_pdf(pdf_output_path)
    finally:
        # Clean up temporary file
        if os.path.exists(temp_html_path):
            os.remove(temp_html_path)
            
    return pdf_output_path